apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dot171628490
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dot171628490 
  name: dot171628490
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dot171628490
    weight: 100 
